version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: authentication
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=authentication
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
